aml: Implement DefOr, DefSubtract and DefLNot opcodes
rust-osdev/acpi pull request #199
Opened 2023-10-03 08:28 UTC by alnyan

This PR implements some simple opcodes currently missing, but required for real-hardware function.

2023-10-05 23:08 UTC, IsaacWoods requested changes
Thanks for submitting this! Always good to get these sorts of opcodes out the way.

Just a few things:

2023-10-05 23:08 UTC, IsaacWoods commented on aml/src/expression.rs
> +            "DefAdd",
This should be `DefSubtract`

2023-10-05 23:08 UTC, IsaacWoods commented on aml/src/expression.rs
> +                (Ok(AmlValue::Boolean(operand)), context)
I might just be missing it, but I don't see where the actual not is happening. Should this be `!operand`?

2023-10-06 07:59 UTC, alnyan commented
Yeah, sorry, these were pretty dumb mistakes I made while copy-pasting code :sweat_smile:

2023-10-06 17:43 UTC, IsaacWoods commented
No worries; I've made plenty! Thanks!

2023-10-06 17:43 UTC, IsaacWoods approved these changes

2023-10-06 17:43 UTC, merged